export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_TASKS_LIST = 'SET_TASKS_LIST';
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_PRIORITY_LIST = 'SET_PRIORITY_LIST';
export const PAGE_SET_TITLE = 'PAGE_SET_TITLE';
export const SET_URL_PARAMS = 'SET_URL_PARAMS';


